apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-svc-deployment
  labels:
    app: auth-svc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-svc
  template:
    metadata:
      labels:
        app: auth-svc
    spec:
      containers:
        - name: auth-svc
          image: sainageswar/kotlang-auth:latest
          env:
            - name: AZURE-KEYVAULT-NAME
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: azureKeyVaultName
          ports:
            - containerPort: 8081
              name: web
            - containerPort: 50051
              name: grpc
