apiVersion: v1
kind: Service
metadata:
  name: auth-svc
  labels:
    app: auth-svc
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8081
      name: web
    - port: 50051
      targetPort: 50051
      name: grpc
  selector:
    app: auth-svc
