name: Docker

on:
  push:
    # Publish `release` as Docker `latest` image.
    branches:
      - master

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

  # Run tests for any PRs.
  pull_request:

env:
  # TODO: Change variable to your image's name.
  IMAGE_NAME: kotlang-auth
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build-service:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Install protoc
        run: sudo apt install -y protobuf-compiler

      - name: Install go-grpc
        run: |
          go get -u google.golang.org/protobuf/cmd/protoc-gen-go
          go install google.golang.org/protobuf/cmd/protoc-gen-go
          go get -u google.golang.org/grpc/cmd/protoc-gen-go-grpc
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc
          echo "${HOME}/go/bin" >> $GITHUB_PATH
          echo "Path is ${GITHUB_PATH}"
      - name: Build
        run: ./build.sh

      - name: Build docker image
        run: docker build -t sainageswar/$IMAGE_NAME:$IMAGE_TAG .

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push image
        run: |
          docker push sainageswar/$IMAGE_NAME:$IMAGE_TAG

  deploy-service:
    needs: build-service
    runs-on: ubuntu-latest

    steps:
      # Required for getting 'kubernetes/*.yml' file.
      - uses: actions/checkout@v2

      - uses: azure/setup-kubectl@v2.0

      - name: Set aks context
        uses: azure/aks-set-context@v1
        with:
          creds: "${{ secrets.AZURE_CREDENTIALS }}"
          cluster-name: KotlangCluster
          resource-group: kotlang

      - name: Set k8s secrets
        uses: azure/k8s-create-secret@v1.1
        with:
          namespace: "default"
          secret-type: "generic"
          arguments: --from-literal=tenantId=${{ secrets.AZURE_TENANT_ID }} --from-literal=clientId=${{ secrets.AZURE_CLIENT_ID }} --from-literal=clientSecret=${{ secrets.AZURE_CLIENT_SECRET }}
          secret-name: azure-ad

      - name: Set ACR credentials
        uses: Azure/k8s-create-secret@v1.1
        with:
          container-registry-username: ${{ secrets.DOCKERHUB_USERNAME }}
          container-registry-password: ${{ secrets.DOCKERHUB_TOKEN }}
          secret-name: registry-credentials

      #- name: AKS Deploy
      #  uses: azure/k8s-deploy@v1.4
      #  with:
      #    action: deploy
      #    manifests: |
      #      kubernetes/deployment.yml
      #      kubernetes/service.yml
      #    images: |
      #      sainageswar/$IMAGE_NAME:$IMAGE_TAG
      #    namespace: default
      #    imagepullsecrets: |
      #      registry-credentials
