name: Docker

on:
  push:
    # Publish `release` as Docker `latest` image.
    branches:
      - release

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*

  # Run tests for any PRs.
  pull_request:

env:
  # TODO: Change variable to your image's name.
  IMAGE_NAME: auth-service

jobs:
  build-service:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Install protoc
        run: sudo apt install -y protobuf-compiler

      - name: Install go-grpc
        run: |
          go get -u google.golang.org/protobuf/cmd/protoc-gen-go
          go install google.golang.org/protobuf/cmd/protoc-gen-go
          go get -u google.golang.org/grpc/cmd/protoc-gen-go-grpc
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc
          echo "${HOME}/go/bin" >> $GITHUB_PATH
          echo "Path is ${GITHUB_PATH}"
      - name: Build
        run: ./build.sh

      - name: Build docker image
        run: docker build -t $IMAGE_NAME .

      - name: Log into registry
        uses: azure/docker-login@v1
        with:
          login-server: kotlangauthsvc.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Push image
        run: |
          docker tag $IMAGE_NAME kotlangauthsvc.azurecr.io/$IMAGE_NAME
          docker push kotlangauthsvc.azurecr.io/$IMAGE_NAME
